
@KOTLIN_BACKEND_PORT = 3000
@KOTLIN_BACKEND_BASE_URL = http://localhost:{{KOTLIN_BACKEND_PORT}}

### Check service health
GET {{KOTLIN_BACKEND_BASE_URL}}/health

### Create a customer
POST {{KOTLIN_BACKEND_BASE_URL}}/customer

### List all customers
GET {{KOTLIN_BACKEND_BASE_URL}}/customers

### Create a product
POST {{KOTLIN_BACKEND_BASE_URL}}/product
Content-Type: application/json

{
  "priceGbx": "1099"
}

### List all products
GET {{KOTLIN_BACKEND_BASE_URL}}/products

### Create an order
POST {{KOTLIN_BACKEND_BASE_URL}}/order
Content-Type: application/json

{
  "customerId": "5d868ea6-31c3-4520-b27a-f23a276d5c6f",
  "products": [
    {
      "productId": "f727a462-bceb-4e53-8c75-7c33290cda99"
    }
  ]
}

### List all orders
GET {{KOTLIN_BACKEND_BASE_URL}}/orders

### Create a payment intent
POST {{KOTLIN_BACKEND_BASE_URL}}/payment-intent
Content-Type: application/json

{
  "orderId": "98f1414a-5805-46f4-840c-95483dee732f",
  "amountGbx": "1099"
}
