
@KOTLIN_BACKEND_PORT = 3000
@KOTLIN_BACKEND_BASE_URL = http://localhost:{{KOTLIN_BACKEND_PORT}}

### Check service health
GET {{KOTLIN_BACKEND_BASE_URL}}/health

### Create a customer
POST {{KOTLIN_BACKEND_BASE_URL}}/customer

### List all customers
GET {{KOTLIN_BACKEND_BASE_URL}}/customers

### Create a product
POST {{KOTLIN_BACKEND_BASE_URL}}/product
Content-Type: application/json

{
  "priceGbx": "1099"
}
