openapi: "3.0.0"
info:
  version: 3.0.0
  title: Stripe Transactions API
paths:
  /health:
    get:
      operationId: getHealth
      tags:
        - health
      description: |
        Endpoint used to verify connectivity.
      responses:
        200:
          description: Health OK.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
  /customer:
    post:
      operationId: createCustomer
      description: |
        Creates a customer.
      tags:
        - customers
      responses:
        201:
          description: Customer created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCustomerSuccessResponse'
  /customers:
    get:
      operationId: listCustomers
      tags:
        - customers
      responses:
        200:
          description: |
            A list of customers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListCustomersSuccessResponse'
components:
  schemas:
    SuccessResponse:
      type: object
      required:
        - ok
      properties:
        ok:
          type: boolean
    ErrorResponse:
      type: object
      required:
        - error
        - msg
      properties:
        error:
          type: string
        msg:
          type: string
    CreateCustomerSuccessResponse:
      type: object
      required:
        - customerId
      properties:
        customerId:
          type: string
          format: uuid
    ListCustomersSuccessResponse:
      type: object
      required:
        - customers
      properties:
        customers:
          type: array
          items:
            type: object
            required:
              - id
            properties:
              id:
                type: string
                format: uuid
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
